### ISSUE TITLE
workernode: Sandbox ID out of range

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#65]
> ###### Originally posted 2015-12-07 14:10 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

```
Dec 06 15:08:46 thjx python[959]: Sandbox ID out of range (allowed: 0-99)
Dec 06 15:08:46 thjx python[959]: Sandbox ID out of range (allowed: 0-99)
Dec 06 15:08:46 thjx python[959]: Sandbox ID out of range (allowed: 0-99)
Dec 06 15:08:46 thjx python[959]: Sandbox ID out of range (allowed: 0-99)
Dec 06 15:15:26 thjx workernode[959]: [ERROR] Server timeout
Dec 06 15:15:26 thjx workernode[959]: [INFO] match 93 done
Dec 06 15:15:26 thjx workernode[959]: [ERROR] Task exception was never retrieved
                                      future: <Task finished coro=<wrapper() done, defined at /var/prologin/venv/lib/python3.5/site-packages/ProloginSADM-1.0-py3.5.egg/prologin/workernode/worker.py:53> except
                                      Traceback (most recent call last):
                                        File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
                                          result = coro.send(value)
                                        File "/var/prologin/venv/lib/python3.5/site-packages/ProloginSADM-1.0-py3.5.egg/prologin/workernode/worker.py", line 63, in wrapper
                                          r = yield from func(self, *wargs, **wkwargs)
                                        File "/var/prologin/venv/lib/python3.5/site-packages/ProloginSADM-1.0-py3.5.egg/prologin/workernode/worker.py", line 226, in run_match
                                          server_stdout, dumper_stdout = task_server.result()
                                      ValueError: too many values to unpack (expected 2)

```

**Comment by seirl** [comment]
> ###### Originally posted 2016-01-17 01:59 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fixed (hopefully) by 7e864a1.
