### ISSUE TITLE
masternode redispatch error

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#87]
```
Apr 29 18:16:31 web.prolo masternode[18085]: [ERROR] Janitor task triggered an exception
                                             Traceback (most recent call last):
                                               File "/var/prologin/venv/lib/python3.6/site-packages/ProloginSADM-1.0-py3.6.egg/prologin/masternode/master.py", line 205, in janitor_task
                                                 self.redispatch_timeout_tasks(worker)
                                               File "/var/prologin/venv/lib/python3.6/site-packages/ProloginSADM-1.0-py3.6.egg/prologin/masternode/master.py", line 184, in redispatch_timeout_tasks
                                                 worker.tasks.pop(i)
                                             IndexError: pop index out of range

```

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/infra/sadm/-/issues/87
