### ISSUE TITLE
Absence du nbd après un ajout dans udb

### ISSUE THREAD

**Issue by Ekleog** [prologin/sadm#88]
Après création d'un user `coproduit` via udb, première connexion (après restart de `nfs-server.service` sur rhfs23), cette erreur.

Note: il avait une tentative de connexion en cours depuis avant le restart de nfs-server, qui n'a pas abouti.

```
May 01 02:56:40 rhfs23.prolo hfs-2[737]: [ERROR] Something wrong happened
                                         Traceback (most recent call last):
                                           File "/var/prologin/venv/lib/python3.6/site-packages/ProloginSADM-1.0-py3.6.egg/prologin/hfs/server.py", line 142, in do_POST
                                             self.migrate_user()
                                           File "/var/prologin/venv/lib/python3.6/site-packages/ProloginSADM-1.0-py3.6.egg/prologin/hfs/server.py", line 162, in migrate_user
                                             with open(self.nbd_filename(), 'rb') as fp:
                                         FileNotFoundError: [Errno 2] No such file or directory: '/export/hfs2/coproduit.nbd'
May 01 02:56:40 rhfs23.prolo systemd-timesyncd[7180]: Network configuration changed, trying to establish connection.
May 01 02:56:40 rhfs23.prolo systemd-timesyncd[7180]: Synchronized to time server 192.168.1.254:123 (ntp.prolo).
May 01 02:56:40 rhfs23.prolo hfs-3[755]: [ERROR] Something wrong happened
                                         Traceback (most recent call last):
                                           File "/var/prologin/venv/lib/python3.6/site-packages/ProloginSADM-1.0-py3.6.egg/prologin/hfs/server.py", line 140, in do_POST
                                             self.get_hfs()
                                           File "/var/prologin/venv/lib/python3.6/site-packages/ProloginSADM-1.0-py3.6.egg/prologin/hfs/server.py", line 201, in get_hfs
                                             self.remote_user_handler(location)
                                           File "/var/prologin/venv/lib/python3.6/site-packages/ProloginSADM-1.0-py3.6.egg/prologin/hfs/server.py", line 348, in remote_user_handler
                                             block = zfp.read(65536)
                                           File "/usr/lib64/python3.6/gzip.py", line 276, in read
                                             return self._buffer.read(size)
                                           File "/usr/lib64/python3.6/_compression.py", line 68, in readinto
                                             data = self.read(len(byte_view))
                                           File "/usr/lib64/python3.6/gzip.py", line 463, in read
                                             if not self._read_gzip_header():
                                           File "/usr/lib64/python3.6/gzip.py", line 411, in _read_gzip_header
                                             raise OSError('Not a gzipped file (%r)' % magic)
                                         OSError: Not a gzipped file (b'HT')
```

**Comment by audebert** [comment]
This issue did not reproduce this year. Closing.
